USE company_db;

INSERT INTO departments (department_name)
VALUES 
    ('EMPLOYEE SERVICES'),
    ('SALES'),
    ('CORPORATE'),
    ('HUMAN RESOURCES'),
    ('MARKETING');

INSERT INTO roles (title, salary, department)
VALUES 
    ('SALES MANAGER', 150000, 'SALES'),
    ('JUNIOR SALES PERSON', 50000, 'SALES'),
    ('CEO', 500000, 'CORPORATE'),
    ('CFO', 400000, 'CORPORATE'),
    ('MARKETING DIRECTOR', 200000, 'MARKETING'),
    ('MARKETING ASSISTANT', 100000, 'MARKETING'),
    ('HEALTH DIRECTOR', 75000, 'HUMAN RESOURCES');

INSERT INTO employees (first_name, last_name, role_title, salary_number, department_id, manager_id)
VALUES
    ('DEVIN', 'GOMEZ', 'CEO', 500000, 'CORPORATE', null),
    ('KEVIN', 'HART', 'CFO', 400000, 'CORPORATE', null),
    ('DWAYNE', 'JOHNSON', 'SALES MANAGER', 150000, 'SALES', 'DEVIN GOMEZ'),
    ('CHRISTIAN', 'BALE', 'SALES PERSON', 50000, 'SALES', 'DWAYNE JOHNSON'),
    ('LEWIS', 'HAMILTON', 'SALES PERSON', 50000, 'SALES', 'DWAYNE JOHNSON'),
    ('SEBASTIAN', 'VETTLE', 'MARKETING DIRECTOR', 200000, 'MARKETING', 'KEVIN HART'),
    ('SERGIO', 'PEREZ', 'MARKETING ASSISTANT', 100000, 'MARKETING', 'SEBASTIAN VETTLE'),
    ('OSCAR', 'PIASTRY', 'SALES PERSON', 50000, 'SALES', 'DWAYNE JOHNSON'),
    ('RUTH', 'CHRIS', 'HEALTH DIRECTOR', 75000, 'HUMAN RESOURCES', 'KEVIN HART'),
    ('SUGE', 'KNIGHT', 'CFO', 400000, 'CORPORATE', null);